[package]
name = "precord"
version = "0.1.3"
authors = ["Xiaopeng Li <x.friday@outlook.com>"]
edition = "2018"
repository = "https://github.com/xiaopengli89/precord"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.15"
futures-timer = "3.0.2"
plotters = "0.3"
clap = "3.0.0-beta.2"

[dependencies.heim]
version = "0.1.0-rc.1"
features = ["process"]

[patch.crates-io.heim]
version = "0.1.0-rc.1"
git = "https://github.com/heim-rs/heim"
rev = "b292f15"
