[package]
name = "precord"
version = "0.1.10"
authors = ["Xiaopeng Li <x.friday@outlook.com>"]
edition = "2018"
repository = "https://github.com/xiaopengli89/precord"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.15"
futures-timer = "3.0.2"
plotters = "0.3"
clap = "3.0.0-beta.2"
bitflags = "1.3.2"

[dependencies.heim]
version = "0.1.0-rc.1"
features = ["process"]

[dependencies.serde]
version = "1.0.127"
features = ["serde_derive"]

[target.'cfg(target_os = "macos")'.dependencies]
plist = "1.2.1"

[target.'cfg(target_os = "windows")'.dependencies]
wmi = "0.9.1"

[patch.crates-io.heim]
version = "0.1.0-rc.1"
git = "https://github.com/xiaopengli89/heim"
rev = "3848144"
