[package]
name = "precord"
version = "0.1.0"
authors = ["李小鹏 <lixiaopeng.jetspark@bytedance.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = "3.2"
plotters = "0.3"
clap = "3.0.0-beta.2"