[package]
name = "precord"
version = "0.2.0"
authors = ["Xiaopeng Li <x.friday@outlook.com>"]
edition = "2021"
repository = "https://github.com/xiaopengli89/precord"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["precord-core"]

[dependencies]
futures = "0.3.15"
futures-timer = "3.0.2"
plotters = "0.3"
clap = "3.0.0-beta.2"
bitflags = "1.3.2"

[dependencies.precord-core]
path = "precord-core"

[dependencies.heim]
version = "0.1.0-rc.1"
features = ["process"]

[patch.crates-io.heim]
version = "0.1.0-rc.1"
git = "https://github.com/xiaopengli89/heim"
rev = "3848144"
