[package]
name = "precord-core"
version = "0.2.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"

[dependencies.serde]
version = "1.0.127"
features = ["serde_derive"]

[target.'cfg(unix)'.dependencies]
libc = "0.2.106"

[target.'cfg(target_os = "macos")'.dependencies]
plist = "1.2.1"

[target.'cfg(target_os = "windows")'.dependencies]
wmi = "0.9.1"
winapi = { version = "0.3.9", features = ["pdh"] }
widestring = "1.0.0-beta.1"

