[package]
name = "precord-core"
version = "0.3.3"
edition = "2021"
authors = ["Xiaopeng Li <x.friday@outlook.com>"]
description = "Library to get process or system performance data"
homepage = "https://github.com/xiaopengli89/precord"
repository = "https://github.com/xiaopengli89/precord"
keywords = ["performance"]
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
sysinfo = "0.21.2"

[dependencies.serde]
version = "1.0.127"
features = ["serde_derive"]

[target.'cfg(target_os = "macos")'.dependencies]
plist = "1.2.1"
core-foundation = "=0.9.1"
IOKit-sys = "0.1.5"

[target.'cfg(target_os = "windows")'.dependencies]
wmi = "0.9.1"
winapi = { version = "0.3.9", features = ["pdh"] }
widestring = "1.0.0-beta.1"
ferrisetw = "0.1.1"
