name: Rust

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Check ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          cargo build
          cargo test
      - name: Build Release macOS
        if: "startsWith(github.ref, 'refs/tags/') && matrix.os == 'macos-latest'"
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.11"
        run : |
          rustup target add aarch64-apple-darwin
          cargo build --release
          cargo test --release
          cargo build --release --target aarch64-apple-darwin
          tar -C target/release -czvf target/precord-macos-x86_64-${{ github.ref_name }}.tar.gz precord
          tar -C target/aarch64-apple-darwin/release -czvf target/precord-macos-aarch64-${{ github.ref_name }}.tar.gz precord
      - name: Build Release Windows x86_64
        if: "startsWith(github.ref, 'refs/tags/') && matrix.os == 'windows-latest'"
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
        run : |
          cargo build --release --target x86_64-pc-windows-msvc
          cargo test --release --target x86_64-pc-windows-msvc
          mv ./target/x86_64-pc-windows-msvc/release/precord.exe ./target/precord-windows-x86_64-${{ github.ref_name }}.exe
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.tar.gz
            target/*.zip
            target/*.exe
